export const name = 'Chaz L';
export const company = 'Service NSW';
export const role = "Software Engineer"
export const email = "contact@caz-dev.com"
export const location = "Sydney, NSW"
export const description = `I'm a ${role} with 5 years of experience located in ${location} and currently employed at ${company}. I'm passionate about creating scalable, clean code and enjoy collaborating with diverse teams.`
export const github = 'https://github.com/cazdev'
export const linkedin = 'https://www.linkedin.com/in/chaz-lambrechtsen'
export const resume = 'https://drive.google.com/file/d/1NAfv29HfhlEzWiF6YJO0E1EEMBmDiPDD/preview'